adding scanning to config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,4 +1,4 @@
-version: 2
+version: 2.1
 jobs:
  build:
   # Variable expansion in working_directory not supported at this time
@@ -9,6 +9,7 @@ jobs:
   steps:
    - checkout
    - setup_remote_docker
+   - ZAP Scan
 
    - run: 
       name: Setup environment
@@ -32,7 +33,33 @@ jobs:
       command: |
           go test \
           github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
+   - run:
+       name: Build application container    
+        command: |    
+          go install --ldflags '-extldflags "-static"' \    
+          github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};    
+          [ ! -e bin ] && mkdir bin;    
+          cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;    
+          docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;    
+   - run:    
+       name: Run application in background    
+        command: |    
+         docker run ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}    
+         background: true    
 
+- run:
+  name: ZAP baseline scan of application
+  # Only fail on error code 1, which indicates at least one FAIL was found.
+  # error codes 2 & 3 indicate WARN or other, and should not break the run
+  command: |
+    (
+ docker pull owasp/zap2docker-weekly && \    
+ docker run -t owasp/zap2docker-weekly zap-baseline.py \    
+ -u https://raw.githubusercontent.com/${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \    
+ -t http://172.17.0.2:8080/ || \    
+    if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+    )
+    
    - deploy:
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
